permalink: pretty
plugins:
  - jekyll-redirect-from
sass:
  style: compressed
exclude:
  # `vendor/` is excluded because of <https://github.com/jekyll/jekyll/issues/3330>
  - vendor/
  - CNAME
  - Gemfile
  - LICENSE.md
  - README.md
  - README_ms.md

liquid:
  error_mode: strict
  strict_filters: true
